export const URL = {
    SIGNIN: "http://localhost:5000/auth/signin",
    SIGNUP: "http://localhost:5000/auth/signup",
    NEW_ACCESS_TOKEN: "http://localhost:5000/auth/refresh-token",
    VERIFY_TOKEN: "http://localhost:5000/auth/verify-token",
    CREATE_ARTICLE: "http://localhost:5000/article/create",
    GET_ALL_ARTICLES: "http://localhost:5000/article",
    GET_SINGLE_ARTICLE: "http://localhost:5000/article",
    EDIT_ARTICLE: "http://localhost:5000/article",
    GET_COMMENT: "http://localhost:5000/comment",
    POST_COMMENT: "http://localhost:5000/comment",
    GET_USERNAME: "http://localhost:5000/user",
    GET_PROFILE: "http://localhost:5000/profile",
    GET_PROFILE_IMAGE: "http://localhost:5000/profile/profile-image",
    GET_CURRENT_USER: "http://localhost:5000/auth/check",
};
